INCDIR=../PGP2/include
LIBDIR=../PGP2/lib
OBJECTS := $(patsubst %.c, %.o, $(wildcard *.c))
CC=gcc

CFLAGS = -I$(INCDIR) -L$(LIBDIR) -fomit-frame-pointer -O2 -Wall -Wextra -lgp2

default:	$(OBJECTS)
		$(CC) $(OBJECTS) $(CFLAGS) -o gp2run

%.o:		%.c
		$(CC) -c $(CFLAGS) -o $@ $<

clean:	
		rm *
